### ISSUE TITLE
allow for connecting to multiple cassandra cluster nodes

### ISSUE THREAD

**Issue by makrisoft** [lpgauth/marina#20]
right now only a single cassandra node can be specified in the config.

**Comment by weixiyen** [comment]
What about just using DNS route to different nodes.

**Comment by weixiyen** [comment]
@lpgauth noticed you had token aware load balancing on the roadmap.  

How are you handling spreading the requests to multiple nodes in production to avoid overloading a single coordinator node?

thanks in advance!

**Comment by lpgauth** [comment]
Hi,
I finally got around implementing a proper pooling strategy for `marina`. It will now first connect to a `bootstrap` node to lookup the `system.peers` table. From that table we gather all peers and open connections to all of them. You can filter nodes by providing `filter_dc`. Currently, the only mode supported is `random` picking, I plan to eventually add `token-aware` picking.

PR: https://github.com/lpgauth/marina/pull/30

Cheers,
LP

**Comment by unbalancedparentheses** [comment]
@lpgauth do you have any update on this?

**Comment by lpgauth** [comment]
@unbalancedparentheses hey, haven't had much time to play with this as we're moving from C* to ScyllaDB and I didn't want to change too many variables at once. Last time I checked the only remaining issue was to fix the prepared statement cache.

**Comment by unbalancedparentheses** [comment]
@lpgauth so if we don't use prepared statements it should be working fine, right? we are moving away from cqerl because it keeps on trying to connect to dead cassandra nodes of a cluster, it doesn't backlist the dead cassandra nodes until they get online.

**Comment by lpgauth** [comment]
@unbalancedparentheses yes, it should, but it's only been testing on one node in production for maybe a week so there might be other bugs.

**Comment by lpgauth** [comment]
This finally came back to the top of my list. Still WIP, but coming soon.
https://github.com/lpgauth/marina/pull/34

**Comment by lpgauth** [comment]
This has finally been merged 🎉
