### ISSUE TITLE
Plaintext cassandra implementation

### ISSUE THREAD

**Issue by neeraj9** [lpgauth/marina#33]
It would be at least necessary to have simple platintext authentication. I have a prototype implementation https://github.com/neeraj9/marina/commit/243ff706be850d3cb0bfa558ebb4753a8bf99547 but is just a simple hack to authenticate. I have tested the patch against cassandra server as well and it works.

**Comment by lpgauth** [comment]
Cool, finishing some major changes and will take a look at the same time. I'll get back to you soon.

**Comment by lpgauth** [comment]
Done in https://github.com/lpgauth/marina/pull/38.
